### ISSUE TITLE
Elm’s Time Traveling Debugger

### ISSUE THREAD

**Issue by danieldocki** [khusnetdinov/elmkit#3]
Sorry, but I'm new to Elm's world. But I'm using your kit to develop a study application and I wanted to be able to enable Elm's Time Traveling Debugger, how can I do that?

Thanks for everything

**Comment by khusnetdinov** [comment]
Do you have other solutions that could be implemented in this repo?  Link for this debugger I will try to implement it or just investigate to problem domain.

**Comment by danieldocki** [comment]
I discovered how to enable.

Have to add `makeParameters` with tag `--debug` in the `brunch-config.js`.

```
      elmBrunch: {
        mainModules: ['src/elm/Application.elm'],
        outputFolder: "public/javascripts/",
        outputFile: "elm.js",
        makeParameters: ['--debug']
      },
```

Maybe put this option in the documentation?

**Comment by khusnetdinov** [comment]
Any way Welcome for PR!
